name = "file-share-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "file-share"

[[d1_databases]]
binding = "DB"
database_name = "files"
database_id = "8566dc48-723e-4802-91fc-2a80c6ecc22a"    # Will be set during deployment
