name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Use a specific Ubuntu version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Deploy to Cloudflare
      run: wrangler deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
